# permissions to do viewer xxxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xxx-viewer-role
rules:
- apiGroups:
  - test.inspur.com
  resources:
  - xxxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.inspur.com
  resources:
  - xxxes/status
  verbs:
  - get
