apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: xxxes.test.inspur.com
spec:
  group: test.inspur.com
  version: v1alpha1
  names:
    kind: Xxx
    plural: xxxes
  scope: Namespaced